//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.20 at 03:15:31 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.lapshina.com/spring/ws/product", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.lapshina.eshop.soap;
